var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("WeakMap",function(a){function b(a){$jscomp.owns(a,d)||$jscomp.defineProperty(a,d,{value:{}})}function c(a){var f=Object[a];f&&(Object[a]=function(a){b(a);return f(a)})}if(function(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),f=Object.seal({}),c=new a([[b,2],[f,3]]);if(2!=c.get(b)||3!=c.get(f))return!1;c.delete(b);c.set(f,4);return!c.has(b)&&4==c.get(f)}catch(h){return!1}}())return a;var d="$jscomp_hidden_"+Math.random().toString().substring(2);c("freeze");c("preventExtensions");
c("seal");var e=0,g=function(a){this.id_=(e+=Math.random()+1).toString();if(a){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};g.prototype.set=function(a,f){b(a);if(!$jscomp.owns(a,d))throw Error("WeakMap key fail: "+a);a[d][this.id_]=f;return this};g.prototype.get=function(a){return $jscomp.owns(a,d)?a[d][this.id_]:void 0};g.prototype.has=function(a){return $jscomp.owns(a,d)&&$jscomp.owns(a[d],this.id_)};g.prototype.delete=
function(a){return $jscomp.owns(a,d)&&$jscomp.owns(a[d],this.id_)?delete a[d][this.id_]:!1};return g},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){if(!$jscomp.ASSUME_NO_NATIVE_MAP&&function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a($jscomp.makeIterator([[b,"s"]]));if("s"!=c.get(b)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var h=c.entries(),d=h.next();if(d.done||d.value[0]!=b||"s"!=d.value[1])return!1;d=h.next();return d.done||4!=d.value[0].x||"t"!=d.value[1]||!h.next().done?!1:!0}catch(l){return!1}}())return a;$jscomp.initSymbol();
$jscomp.initSymbolIterator();var b=new WeakMap,c=function(a){this.data_={};this.head_=g();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};c.prototype.set=function(a,b){var f=d(this,a);f.list||(f.list=this.data_[f.id]=[]);f.entry?f.entry.value=b:(f.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,value:b},f.list.push(f.entry),this.head_.previous.next=f.entry,this.head_.previous=f.entry,this.size++);return this};c.prototype.delete=
function(a){a=d(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=g();this.size=0};c.prototype.has=function(a){return!!d(this,a).entry};c.prototype.get=function(a){return(a=d(this,a).entry)&&a.value};c.prototype.entries=function(){return e(this,function(a){return[a.key,
a.value]})};c.prototype.keys=function(){return e(this,function(a){return a.key})};c.prototype.values=function(){return e(this,function(a){return a.value})};c.prototype.forEach=function(a,b){for(var c=this.entries(),d;!(d=c.next()).done;)d=d.value,a.call(b,d[1],d[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(a,c){var d=c&&typeof c;"object"==d||"function"==d?b.has(c)?d=b.get(c):(d=""+ ++k,b.set(c,d)):d="p_"+c;var f=a.data_[d];if(f&&$jscomp.owns(a.data_,d))for(a=0;a<f.length;a++){var e=
f[a];if(c!==c&&e.key!==e.key||c===e.key)return{id:d,list:f,index:a,entry:e}}return{id:d,list:f,index:-1,entry:void 0}},e=function(a,b){var c=a.head_;return $jscomp.iteratorPrototype(function(){if(c){for(;c.head!=a.head_;)c=c.previous;for(;c.next!=c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})},g=function(){var a={};return a.previous=a.next=a.head=a},k=0;return c},"es6","es3");
$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var g=a[e];if(b.call(c,g,e,a))return{i:e,v:g}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");Map=function(){this.map={}};
Map.prototype={put:function(a,b){this.map[a]=b},get:function(a){return this.map[a]},containsKey:function(a){return a in this.map},containsValue:function(a){for(var b in this.map)if(this.map[b]==a)return!0;return!1},isEmpty:function(a){return 0==this.size()},clear:function(){for(var a in this.map)delete this.map[a]},remove:function(a){delete this.map[a]},keys:function(){var a=[],b;for(b in this.map)a.push(b);return a},values:function(){var a=[],b;for(b in this.map)a.push(this.map[b]);return a},size:function(){var a=
0,b;for(b in this.map)a++;return a}};Number.prototype.format=function(){str=String(this);return str.format()};Number.prototype.unFormat=function(){str=String(this);return str.unFormat()};Number.prototype.amountUp=function(){if(1E3>this)return this+1;if(1E3<=this&&5E3>this)return this+5;if(5E3<=this&&1E4>this)return this+10;if(1E4<=this&&1E5>this)return this+50;if(1E5<=this&&1E6>this)return this+100;if(1E6<=this&&1E7>this)return this+500;if(1E7<=this)return this+1E3};
Number.prototype.amountDown=function(){if(1E3>this)return this-1;if(1E3<=this&&5E3>this)return this-5;if(5E3<=this&&1E4>this)return this-10;if(1E4<=this&&1E5>this)return this-50;if(1E5<=this&&1E6>this)return this-100;if(1E6<=this&&1E7>this)return this-500;if(1E7<=this)return this-1E3};Number.prototype.dateOrTime=function(){var a=new Date(this),b=new Date;return a.getDate()===b.getDate()?moment(a,"YYYY-MM-DD HH:mm:ss").format("HH:mm:ss"):moment(a,"YYYY-MM-DD HH:mm:ss").format("YY.MM.DD")};
Number.prototype.strongQty=function(a,b){if(0===b)return""===a?parseInt(this).format():"<span "+a+">"+parseInt(this).format()+"</span>";b=(new Decimal(parseFloat(this))).toFixed(b).format();return""===a?b:"<span "+a+">"+b+"</span>"};Number.prototype.valueCurrency=function(a){return this.toString().valueCurrency(a)};Number.prototype.isNumberic=function(a){return this.toString().isNumberic(a)};Number.prototype.decimalFloor=function(a){var b=Math.pow(10,a);return(Math.floor(this*b)/b).toFixed(a)};
Number.prototype.decimalCeiling=function(a){var b=Math.pow(10,a);return(Math.ceil(this*b)/b).toFixed(a)};String.prototype.format=function(){var a=this.split(".");return a[0].replace(/\B(?=(\d{3})+(?!\d))/g,",")+(a[1]?"."+a[1]:"")};String.prototype.unFormat=function(){return this.replace(/,/g,"")};String.prototype.amountUp=function(){var a=parseFloat(this);return isNaN(a)?"0":a.amountUp()};String.prototype.amountDown=function(){var a=parseFloat(this);return isNaN(a)?"0":a.amountDown()};
String.prototype.strongQty=function(a,b){var c=parseFloat(this);return isNaN(c)?"0":c.strongQty(a,b)};String.prototype.dateOrTime=function(){var a=new Date;return(new Date(this)).getDate()===a.getDate()?moment(this,"YYYY-MM-DD HH:mm:ss").format("HH:mm:ss"):moment(this,"YYYY-MM-DD HH:mm:ss").format("YY.MM.DD")};String.prototype.valueCurrency=function(a){return this+" "+a.toUpperCase()};
String.prototype.isNumberic=function(a){num=this.replace(/^\s+|\s+$/g,"");return("undefined"===typeof a||"1"===a?/^[+\-]?(([1-9][0-9]{0,2}(,[0-9]{3})*)|[0-9]+){1}(\.[0-9]+)?$/g:"2"==a?/^(([1-9][0-9]{0,2}(,[0-9]{3})*)|[0-9]+){1}(\.[0-9]+)?$/g:"3"==a?/^[0-9]+(\.[0-9]+)?$/g:/^[0-9]$/g).test(num)?(num=num.replace(/,/g,""),isNaN(num)?!1:!0):!1};String.prototype.decimalFloor=function(a){return parseFloat(this).decimalFloor(a)};String.prototype.decimalCeiling=function(a){return parseFloat(this).decimalCeiling(a)};
var maxLengthCheck=function(a){a.value.length>a.maxLength&&(a.value=a.value.slice(0,a.maxLength))};$("#gnb-stock").click(function(){"none"===$("#box6").css("display")?$("#box6").toggle("slide",{direction:"right"},300):window.location.href="/stock/eth-btc"});
var waitingDialog=waitingDialog||function(a){var b=a('<div class="modal fade" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-hidden="true" style="padding-top:15%; overflow-y:visible;"><div class="modal-dialog modal-m"><div class="modal-content"><div class="modal-header"><h3 style="margin:0;"></h3></div><div class="modal-body"><div class="progress progress-striped active" style="margin-bottom:0;"><div class="progress-bar" style="width: 100%"></div></div></div></div></div></div>');return{show:function(c,
d){"undefined"===typeof d&&(d={});"undefined"===typeof c&&(c="Loading");var e=a.extend({dialogSize:"m",progressType:"",onHide:null},d);b.find(".modal-dialog").attr("class","modal-dialog").addClass("modal-"+e.dialogSize);b.find(".progress-bar").attr("class","progress-bar");e.progressType&&b.find(".progress-bar").addClass("progress-bar-"+e.progressType);b.find("h3").text(c);if("function"===typeof e.onHide)b.off("hidden.bs.modal").on("hidden.bs.modal",function(a){e.onHide.call(b)});b.modal()},hide:function(){b.modal("hide")}}}(jQuery);
$(document).ready(function(){$(document).on("keypress","[data-input=number]",function(a){a=a.which?a.which:a.keyCode;if(31<a&&(48>a||57<a))return!1;a=$(this);var b=a.attr("maxlength");$.isNumeric(b)&&a.val().length!==b&&a.val(a.val().substr(0,b))});$(document).on("focus","input[type=number]",function(a){$(this).on("mousewheel.disableScroll",function(a){a.preventDefault()})});$(document).on("blur","input[type=number]",function(a){$(this).off("mousewheel.disableScroll")})});
